export const ProductsData = [
  {
    id: "1",
    title: "Gold Hoop Earrings",
    slug: "gold-hoop-earrings",
    price: "1,000",
    image: "https://minas-designs.com/wp-content/uploads/2025/03/A-1500-VICTORY-WINGS-S-min.jpg",
    hoverImage: "https://minas-designs.com/wp-content/uploads/2025/07/a1500.jpg",
  },
  {
    id: "2",
    title: "Silver Chain Necklace",
    slug: "silver-chain-necklace",
    price: "2,500",
    image: "https://minas-designs.com/wp-content/uploads/2025/02/E-1000-S-THE-TWISTED-EARRINGS-min.jpg",
    hoverImage: "https://minas-designs.com/wp-content/uploads/2025/02/twisted-g-hq2.jpg",
  },
  {
    id: "3",
    title: "Emerald Ring",
    slug: "emerald-ring",
    price: "3,200",
    image: "https://minas-designs.com/wp-content/uploads/2025/02/E-960-S-THE-CLIO-EARRINGS-min.jpg",
    hoverImage: "https://minas-designs.com/wp-content/uploads/2025/03/3-min.jpg",
  },
  {
    id: "4",
    title: "Diamond Pendant",
    slug: "diamond-pendant",
    price: "4,500",
    image: "https://minas-designs.com/wp-content/uploads/2025/02/E-961-S-FORCE-MAJEURE-EARRINGS-min.jpg",
    hoverImage: "https://minas-designs.com/wp-content/uploads/2025/02/e961-g-hq.jpg",
  },
  {
    id: "6",
    title: "Rose Gold Anklet",
    slug: "rose-gold-anklet",
    price: "1,200",
    image: "https://minas-designs.com/wp-content/uploads/2025/03/R-393-DELOS-RING-S-min.jpg",
    hoverImage: "https://minas-designs.com/wp-content/uploads/2025/07/4.jpg",
  },
  {
    id: "7",
    title: "Sapphire Earrings",
    slug: "sapphire-earrings",
    price: "2,700",
    image: "https://minas-designs.com/wp-content/uploads/2025/03/R-190-ENOSIS-RING-SG-CORRECT-min.jpg",
    hoverImage: "https://minas-designs.com/wp-content/uploads/2025/07/r-190.jpg",
  },
  {
    id: "8",
    title: "Ruby Ring",
    slug: "ruby-ring",
    price: "3,800",
    image: "https://minas-designs.com/wp-content/uploads/2025/03/R-237-OPSIS-RING-S-min.jpg",
    hoverImage: "https://minas-designs.com/wp-content/uploads/2025/07/r-237-2.jpg",
  },
  {
    id: "9",
    title: "Ruby Ring",
    slug: "ruby-ring",
    price: "3,800",
    image: "https://minas-designs.com/wp-content/uploads/2025/02/C-240-S-UNIVERSAL-JOINT-CHOCKER-min.jpg",
    hoverImage: "https://minas-designs.com/wp-content/uploads/2025/07/c-240.jpg",
  },
  {
    id: "10",
    title: "Ruby Ring",
    slug: "ruby-ring",
    price: "3,800",
    image: "https://minas-designs.com/wp-content/uploads/2025/03/A-297-THE-GOLDEN-POUCH-min.jpg",
    hoverImage: "https://minas-designs.com/wp-content/uploads/2025/07/a297-1.jpg",
  },
];
